# Model
model: yolov8m.pt
pretrained: true

# Data
data: data/hockeyai/yolo/data.yaml

# Training
epochs: 50
patience: 10
batch: 16
imgsz: 1280
workers: 4

# Optimization
optimizer: AdamW
lr0: 0.001
weight_decay: 0.0005

# Output
project: /sfs/gpfs/tardis/home/pbp8nq/Documents/hockey-puck-detection/results
name: hockeyai_baseline
save_period: 5